{
 "title": "Server",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overall server management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No. search requests",
   "type": "stat",
   "description": "Total number of search requests",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "search_image_requests_counter_total{method=\"post\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg search request response time [5m]",
   "type": "gauge",
   "description": "Average response time of all image search requests  measured over the last 5 minutes",
   "gridPos": { "h": 5, "w": 10, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/search-image\", method=\"POST\"}[5m]) /rate(http_request_duration_seconds_count{handler=\"/search-image\", method=\"POST\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of statisfied search requests  [0.5s]",
   "type": "gauge",
   "description": "Percentage of requests with response time below 0.5s",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{le=\"0.5\", job=\"otel-search-image-metrics\"}[5m])) / sum(rate(http_request_duration_seconds_count{job=\"otel-search-image-metrics\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. img encoding requests",
   "type": "stat",
   "description": "Total number of image encoding requests",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "encoding_requests_total{method=\"post\", endpoint=\"/encode-image\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. text encoding requests",
   "type": "stat",
   "description": "Total number of text encoding requests",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "encoding_requests_total{method=\"post\", endpoint=\"/encode-text\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg img encoding response time [5m]",
   "type": "gauge",
   "description": "Average response time of all image encoding requests measured over the last 5 minutes",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/encode-image\", method=\"POST\"}[5m]) / rate(http_request_duration_seconds_count{handler=\"/encode-image\", method=\"POST\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg text encoding response time [5m]",
   "type": "gauge",
   "description": "Average response time of all text encoding requests measured over the last 5 minutes",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/encode-text\", method=\"POST\"}[5m]) / rate(http_request_duration_seconds_count{handler=\"/encode-text\", method=\"POST\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No. workers [app]",
   "type": "stat",
   "description": "Number of active workers of App service",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_active_workers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "No. workers [model]",
   "type": "stat",
   "description": "Number of active workers of Model serving service",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clip_active_workers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Detail performance charts illustration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "description": "Average response time of all requests of each service over the last measured interval",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/search-image\", method=\"POST\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{handler=\"/search-image\", method=\"POST\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/encode_image\", method=\"POST\"}[5m]) / rate(http_request_duration_seconds_count{handler=\"/encode_image\", method=\"POST\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/encode_text\", method=\"POST\"}[5m]) / rate(http_request_duration_seconds_count{handler=\"/encode_text\", method=\"POST\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of satisfied requests  [0.5s]",
   "type": "timeseries",
   "description": "Percentage of total requests with response time below 0.5s of all services over the measured interval",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{le=\"0.5\"}[$__rate_interval])) by (job) / sum(rate(http_request_duration_seconds_count[$__rate_interval])) by (job) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}