services:
  app:
    hostname: app
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENTRY_PROXY: ${ENTRY_PROXY}
    image: text-to-image-retrieval/app
    ports:
      - "8008:8008"
    environment:
      PROMETHEUS_MULTIPROC_DIR: /app/prometheus_multiproc
    volumes:
      - ./logs:/app/logs
      - ./prometheus_multiproc:/app/prometheus_multiproc
      - ./../etl:/app/etl
    command: gunicorn -c gunicorn_conf.py app:app
    networks:
      - text_to_image_retrieval_network
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    environment:
      NO_PROXY: localhost,app,streamlit,${NETWORK_SUBNET}
      no_proxy: localhost,app,streamlit,${NETWORK_SUBNET}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - text_to_image_retrieval_network
    env_file:
      - .env
  
networks:
  text_to_image_retrieval_network:
    name: text_to_image_retrieval_network
    external: true