# Reference: https://github.com/elastic/elasticsearch/blob/main/distribution/docker/src/docker/config/elasticsearch.yml
cluster.name: "docker-cluster"
network.host: 0.0.0.0

# See: https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
xpack.security.enabled: true
