# Reference: ## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.username: "kibana_system"
elasticsearch.password: "${ELASTIC_PASSWORD}"

xpack.security.encryptionKey: "${KIBANA_ENCRYPTION_KEY}"
xpack.encryptedSavedObjects.encryptionKey: "${KIBANA_ENCRYPTION_KEY}"

# See https://www.elastic.co/guide/en/kibana/8.15/fleet-settings-kb.html#fleet-data-visualizer-settings to allow access to Elastic Package Manager registry
xpack.fleet.registryProxyUrl: "${HTTPS_PROXY}"